(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INIT_POS_GNSS-VAL
          INIT_POS_GNSS
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          USE_PREDICT_POSE-VAL
          USE_PREDICT_POSE
          ERROR_THRESHOLD-VAL
          ERROR_THRESHOLD
          RESOLUTION-VAL
          RESOLUTION
          STEP_SIZE-VAL
          STEP_SIZE
          TRANS_EPSILON-VAL
          TRANS_EPSILON
          MAX_ITERATIONS-VAL
          MAX_ITERATIONS
))