(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          OTHERS_DISTANCE-VAL
          OTHERS_DISTANCE
          DETECTION_RANGE-VAL
          DETECTION_RANGE
          THRESHOLD_POINTS-VAL
          THRESHOLD_POINTS
          DETECTION_HEIGHT_TOP-VAL
          DETECTION_HEIGHT_TOP
          DETECTION_HEIGHT_BOTTOM-VAL
          DETECTION_HEIGHT_BOTTOM
          DECELERATION-VAL
          DECELERATION
          VELOCITY_CHANGE_LIMIT-VAL
          VELOCITY_CHANGE_LIMIT
          DECELERATION_RANGE-VAL
          DECELERATION_RANGE
          TEMPORAL_WAYPOINTS_SIZE-VAL
          TEMPORAL_WAYPOINTS_SIZE
))