(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DISTANCE_THRESHOLD_NEIGHBOR_LANES-VAL
          DISTANCE_THRESHOLD_NEIGHBOR_LANES
          LANE_CHANGE_INTERVAL-VAL
          LANE_CHANGE_INTERVAL
          LANE_CHANGE_TARGET_RATIO-VAL
          LANE_CHANGE_TARGET_RATIO
          LANE_CHANGE_TARGET_MINIMUM-VAL
          LANE_CHANGE_TARGET_MINIMUM
          VECTOR_LENGTH_HERMITE_CURVE-VAL
          VECTOR_LENGTH_HERMITE_CURVE
))