(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSOR_HEIGHT-VAL
          SENSOR_HEIGHT
          CLIPPING_HEIGHT-VAL
          CLIPPING_HEIGHT
          MIN_POINT_DISTANCE-VAL
          MIN_POINT_DISTANCE
          RADIAL_DIVIDER_ANGLE-VAL
          RADIAL_DIVIDER_ANGLE
          CONCENTRIC_DIVIDER_DISTANCE-VAL
          CONCENTRIC_DIVIDER_DISTANCE
          LOCAL_MAX_SLOPE-VAL
          LOCAL_MAX_SLOPE
          GENERAL_MAX_SLOPE-VAL
          GENERAL_MAX_SLOPE
          MIN_HEIGHT_THRESHOLD-VAL
          MIN_HEIGHT_THRESHOLD
          RECLASS_DISTANCE_THRESHOLD-VAL
          RECLASS_DISTANCE_THRESHOLD
))