(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCELERATION-VAL
          ACCELERATION
          STOPLINE_SEARCH_RADIUS-VAL
          STOPLINE_SEARCH_RADIUS
          NUMBER_OF_ZEROS_AHEAD-VAL
          NUMBER_OF_ZEROS_AHEAD
          NUMBER_OF_ZEROS_BEHIND-VAL
          NUMBER_OF_ZEROS_BEHIND
          NUMBER_OF_SMOOTHING_COUNT-VAL
          NUMBER_OF_SMOOTHING_COUNT
))