(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PARAM_FLAG-VAL
          PARAM_FLAG
          VELOCITY-VAL
          VELOCITY
          LOOKAHEAD_DISTANCE-VAL
          LOOKAHEAD_DISTANCE
          LOOKAHEAD_RATIO-VAL
          LOOKAHEAD_RATIO
          MINIMUM_LOOKAHEAD_DISTANCE-VAL
          MINIMUM_LOOKAHEAD_DISTANCE
          DISPLACEMENT_THRESHOLD-VAL
          DISPLACEMENT_THRESHOLD
          RELATIVE_ANGLE_THRESHOLD-VAL
          RELATIVE_ANGLE_THRESHOLD
))