(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INIT_POS_GNSS-VAL
          INIT_POS_GNSS
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          USE_PREDICT_POSE-VAL
          USE_PREDICT_POSE
          ERROR_THRESHOLD-VAL
          ERROR_THRESHOLD
          MAXIMUM_ITERATIONS-VAL
          MAXIMUM_ITERATIONS
          TRANSFORMATION_EPSILON-VAL
          TRANSFORMATION_EPSILON
          MAX_CORRESPONDENCE_DISTANCE-VAL
          MAX_CORRESPONDENCE_DISTANCE
          EUCLIDEAN_FITNESS_EPSILON-VAL
          EUCLIDEAN_FITNESS_EPSILON
          RANSAC_OUTLIER_REJECTION_THRESHOLD-VAL
          RANSAC_OUTLIER_REJECTION_THRESHOLD
))