(cl:in-package dink_for_config_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INITIAL_LIFESPAN-VAL
          INITIAL_LIFESPAN
          DEFAULT_LIFESPAN-VAL
          DEFAULT_LIFESPAN
          NOISE_COVARIANCE-VAL
          NOISE_COVARIANCE
          MEASUREMENT_NOISE_COVARIANCE-VAL
          MEASUREMENT_NOISE_COVARIANCE
          ERROR_ESTIMATE_COVARIANCE-VAL
          ERROR_ESTIMATE_COVARIANCE
          PERCENTAGE_OF_OVERLAPPING-VAL
          PERCENTAGE_OF_OVERLAPPING
          ORB_FEATURES-VAL
          ORB_FEATURES
          USE_ORB-VAL
          USE_ORB
))