(cl:in-package dink_for_msgs-msg)
(cl:export '(GID-VAL
          GID
          LID-VAL
          LID
          POSE-VAL
          POSE
          TWIST-VAL
          TWIST
          DTLANE-VAL
          DTLANE
          CHANGE_FLAG-VAL
          CHANGE_FLAG
          WPSTATE-VAL
          WPSTATE
          LANE_ID-VAL
          LANE_ID
          LEFT_LANE_ID-VAL
          LEFT_LANE_ID
          RIGHT_LANE_ID-VAL
          RIGHT_LANE_ID
          STOP_LINE_ID-VAL
          STOP_LINE_ID
          COST-VAL
          COST
          TIME_COST-VAL
          TIME_COST
          DIRECTION-VAL
          DIRECTION
))