(cl:in-package dink_for_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          CLOUD-VAL
          CLOUD
          MIN_POINT-VAL
          MIN_POINT
          MAX_POINT-VAL
          MAX_POINT
          AVG_POINT-VAL
          AVG_POINT
          CENTROID_POINT-VAL
          CENTROID_POINT
          ESTIMATED_ANGLE-VAL
          ESTIMATED_ANGLE
          DIMENSIONS-VAL
          DIMENSIONS
          EIGEN_VALUES-VAL
          EIGEN_VALUES
          EIGEN_VECTORS-VAL
          EIGEN_VECTORS
          FPFH_DESCRIPTOR-VAL
          FPFH_DESCRIPTOR
          BOUNDING_BOX-VAL
          BOUNDING_BOX
          CONVEX_HULL-VAL
          CONVEX_HULL
          INDICATOR_STATE-VAL
          INDICATOR_STATE
))