(cl:in-package dink_for_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IMAGE_RAW-VAL
          IMAGE_RAW
          POINTS_RAW-VAL
          POINTS_RAW
          POINTS_IMAGE-VAL
          POINTS_IMAGE
          VSCAN_POINTS-VAL
          VSCAN_POINTS
          VSCAN_IMAGE-VAL
          VSCAN_IMAGE
          IMAGE_OBJ-VAL
          IMAGE_OBJ
          IMAGE_OBJ_RANGED-VAL
          IMAGE_OBJ_RANGED
          IMAGE_OBJ_TRACKED-VAL
          IMAGE_OBJ_TRACKED
          CURRENT_POSE-VAL
          CURRENT_POSE
          OBJ_LABEL-VAL
          OBJ_LABEL
          CLUSTER_CENTROIDS-VAL
          CLUSTER_CENTROIDS
          OBJ_POSE-VAL
          OBJ_POSE
          EXECUTION_TIME-VAL
          EXECUTION_TIME
          CYCLE_TIME-VAL
          CYCLE_TIME
          TIME_DIFF-VAL
          TIME_DIFF
))