(cl:in-package tf_server-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          IMAGE_FRAME-VAL
          IMAGE_FRAME
          X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          ANGLE-VAL
          ANGLE
          ROI_IMAGE-VAL
          ROI_IMAGE
          INDICATOR_STATE-VAL
          INDICATOR_STATE
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          USER_DEFINED_INFO-VAL
          USER_DEFINED_INFO
))