(cl:defpackage perception_msgs-msg
  (:use )
  (:export
   "<CIPV>"
   "CIPV"
   "<CIPVTRACK>"
   "CIPVTRACK"
   "<LANE>"
   "LANE"
   "<LANEMODELS>"
   "LANEMODELS"
   "<OBJECT>"
   "OBJECT"
   "<OBJECTARRAY>"
   "OBJECTARRAY"
   "<OBJECTWITHCOVARIANCE>"
   "OBJECTWITHCOVARIANCE"
   "<OBJECTWITHCOVARIANCEARRAY>"
   "OBJECTWITHCOVARIANCEARRAY"
   "<SOLIDPRIMITIVEWITHCOVARIANCE>"
   "SOLIDPRIMITIVEWITHCOVARIANCE"
  ))

