# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dink_for_config_msgs/ConfigCompareMapFilter.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ConfigCompareMapFilter(genpy.Message):
  _md5sum = "09db74a6997527a611ebec850731c83b"
  _type = "dink_for_config_msgs/ConfigCompareMapFilter"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 distance_threshold
float32 min_clipping_height
float32 max_clipping_height
"""
  __slots__ = ['distance_threshold','min_clipping_height','max_clipping_height']
  _slot_types = ['float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       distance_threshold,min_clipping_height,max_clipping_height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConfigCompareMapFilter, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.distance_threshold is None:
        self.distance_threshold = 0.
      if self.min_clipping_height is None:
        self.min_clipping_height = 0.
      if self.max_clipping_height is None:
        self.max_clipping_height = 0.
    else:
      self.distance_threshold = 0.
      self.min_clipping_height = 0.
      self.max_clipping_height = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f().pack(_x.distance_threshold, _x.min_clipping_height, _x.max_clipping_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.distance_threshold, _x.min_clipping_height, _x.max_clipping_height,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f().pack(_x.distance_threshold, _x.min_clipping_height, _x.max_clipping_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.distance_threshold, _x.min_clipping_height, _x.max_clipping_height,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
