(cl:in-package platform_comm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DOOR_OPEN_FRONT_RIGHT-VAL
          DOOR_OPEN_FRONT_RIGHT
          DOOR_OPEN_FRONT_LEFT-VAL
          DOOR_OPEN_FRONT_LEFT
          DOOR_OPEN_REAR_RIGHT-VAL
          DOOR_OPEN_REAR_RIGHT
          DOOR_OPEN_REAR_LEFT-VAL
          DOOR_OPEN_REAR_LEFT
          HOOD_OPEN-VAL
          HOOD_OPEN
          TRUNK_OPEN-VAL
          TRUNK_OPEN
          PASSENGER_PRESENT-VAL
          PASSENGER_PRESENT
          PASSENGER_AIRBAG_ENABLED-VAL
          PASSENGER_AIRBAG_ENABLED
          SEATBELT_ENGAGED_DRIVER-VAL
          SEATBELT_ENGAGED_DRIVER
          SEATBELT_ENGAGED_PASSENGER-VAL
          SEATBELT_ENGAGED_PASSENGER
))