(cl:in-package platform_comm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BTN_VOL_UP-VAL
          BTN_VOL_UP
          BTN_VOL_DOWN-VAL
          BTN_VOL_DOWN
          BTN_MUTE-VAL
          BTN_MUTE
          BTN_NEXT-VAL
          BTN_NEXT
          BTN_PREV-VAL
          BTN_PREV
          BTN_NEXT_HANG_UP-VAL
          BTN_NEXT_HANG_UP
          BTN_PREV_ANSWER-VAL
          BTN_PREV_ANSWER
          BTN_HANG_UP-VAL
          BTN_HANG_UP
          BTN_ANSWER-VAL
          BTN_ANSWER
          BTN_PLAY-VAL
          BTN_PLAY
          BTN_PAUSE-VAL
          BTN_PAUSE
          BTN_PLAY_PAUSE-VAL
          BTN_PLAY_PAUSE
          BTN_MODE-VAL
          BTN_MODE
))