(cl:in-package platform_comm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BTN_CC_ON-VAL
          BTN_CC_ON
          BTN_CC_OFF-VAL
          BTN_CC_OFF
          BTN_CC_ON_OFF-VAL
          BTN_CC_ON_OFF
          BTN_CC_SET_INC-VAL
          BTN_CC_SET_INC
          BTN_CC_SET_DEC-VAL
          BTN_CC_SET_DEC
          BTN_CC_RES-VAL
          BTN_CC_RES
          BTN_CC_CNCL-VAL
          BTN_CC_CNCL
          BTN_CC_RES_CNCL-VAL
          BTN_CC_RES_CNCL
          BTN_ACC_GAP_INC-VAL
          BTN_ACC_GAP_INC
          BTN_ACC_GAP_DEC-VAL
          BTN_ACC_GAP_DEC
          BTN_LKA_ON-VAL
          BTN_LKA_ON
          BTN_LKA_OFF-VAL
          BTN_LKA_OFF
          BTN_LKA_ON_OFF-VAL
          BTN_LKA_ON_OFF
))