(cl:in-package dink_for_can_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TM-VAL
          TM
          DEVMODE-VAL
          DEVMODE
          DRVCONTMODE-VAL
          DRVCONTMODE
          DRVOVERRIDEMODE-VAL
          DRVOVERRIDEMODE
          DRVSERVO-VAL
          DRVSERVO
          DRIVEPEDAL-VAL
          DRIVEPEDAL
          TARGETPEDALSTR-VAL
          TARGETPEDALSTR
          INPUTPEDALSTR-VAL
          INPUTPEDALSTR
          TARGETVELOC-VAL
          TARGETVELOC
          SPEED-VAL
          SPEED
          DRIVESHIFT-VAL
          DRIVESHIFT
          TARGETSHIFT-VAL
          TARGETSHIFT
          INPUTSHIFT-VAL
          INPUTSHIFT
          STRMODE-VAL
          STRMODE
          STRCONTMODE-VAL
          STRCONTMODE
          STROVERRIDEMODE-VAL
          STROVERRIDEMODE
          STRSERVO-VAL
          STRSERVO
          TARGETTORQUE-VAL
          TARGETTORQUE
          TORQUE-VAL
          TORQUE
          ANGLE-VAL
          ANGLE
          TARGETANGLE-VAL
          TARGETANGLE
          BBRAKEPRESS-VAL
          BBRAKEPRESS
          BRAKEPEDAL-VAL
          BRAKEPEDAL
          BRTARGETPEDALSTR-VAL
          BRTARGETPEDALSTR
          BRINPUTPEDALSTR-VAL
          BRINPUTPEDALSTR
          BATTERY-VAL
          BATTERY
          VOLTAGE-VAL
          VOLTAGE
          ANP-VAL
          ANP
          BATTMAXTEMPARATURE-VAL
          BATTMAXTEMPARATURE
          BATTMINTEMPARATURE-VAL
          BATTMINTEMPARATURE
          MAXCHGCURRENT-VAL
          MAXCHGCURRENT
          MAXDISCHGCURRENT-VAL
          MAXDISCHGCURRENT
          SIDEACC-VAL
          SIDEACC
          ACCELLFROMP-VAL
          ACCELLFROMP
          ANGLEFROMP-VAL
          ANGLEFROMP
          BRAKEPEDALFROMP-VAL
          BRAKEPEDALFROMP
          SPEEDFR-VAL
          SPEEDFR
          SPEEDFL-VAL
          SPEEDFL
          SPEEDRR-VAL
          SPEEDRR
          SPEEDRL-VAL
          SPEEDRL
          VELOCFROMP2-VAL
          VELOCFROMP2
          DRVMODE-VAL
          DRVMODE
          DEVPEDALSTRFROMP-VAL
          DEVPEDALSTRFROMP
          RPM-VAL
          RPM
          VELOCFLFROMP-VAL
          VELOCFLFROMP
          EV_MODE-VAL
          EV_MODE
          TEMP-VAL
          TEMP
          SHIFTFRMPRIUS-VAL
          SHIFTFRMPRIUS
          LIGHT-VAL
          LIGHT
          GASLEVEL-VAL
          GASLEVEL
          DOOR-VAL
          DOOR
          CLUISE-VAL
          CLUISE
))