// Generated by gencpp from file dink_for_can_msgs/CANData.msg
// DO NOT EDIT!


#ifndef dink_for_CAN_MSGS_MESSAGE_CANDATA_H
#define dink_for_CAN_MSGS_MESSAGE_CANDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dink_for_can_msgs
{
template <class ContainerAllocator>
struct CANData_
{
  typedef CANData_<ContainerAllocator> Type;

  CANData_()
    : header()
    , count(0)
    , id(0)
    , time(0)
    , flag(0)  {
    }
  CANData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0)
    , id(0)
    , time(0)
    , flag(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _count_type;
  _count_type count;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint32_t _time_type;
  _time_type time;

   typedef uint16_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::dink_for_can_msgs::CANData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dink_for_can_msgs::CANData_<ContainerAllocator> const> ConstPtr;

}; // struct CANData_

typedef ::dink_for_can_msgs::CANData_<std::allocator<void> > CANData;

typedef boost::shared_ptr< ::dink_for_can_msgs::CANData > CANDataPtr;
typedef boost::shared_ptr< ::dink_for_can_msgs::CANData const> CANDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dink_for_can_msgs::CANData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dink_for_can_msgs::CANData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dink_for_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dink_for_can_msgs': ['/home/dink/DINK/ros/src/msgs/dink_for_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dink_for_can_msgs::CANData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dink_for_can_msgs::CANData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dink_for_can_msgs::CANData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3364528f120c0215964c8aca9e410a19";
  }

  static const char* value(const ::dink_for_can_msgs::CANData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3364528f120c0215ULL;
  static const uint64_t static_value2 = 0x964c8aca9e410a19ULL;
};

template<class ContainerAllocator>
struct DataType< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dink_for_can_msgs/CANData";
  }

  static const char* value(const ::dink_for_can_msgs::CANData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 count\n\
uint32 id\n\
uint32 time\n\
uint16 flag\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dink_for_can_msgs::CANData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.id);
      stream.next(m.time);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dink_for_can_msgs::CANData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dink_for_can_msgs::CANData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
    s << indent << "flag: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // dink_for_CAN_MSGS_MESSAGE_CANDATA_H
