(cl:in-package vector_map_msgs-msg)
(cl:export '(LNID-VAL
          LNID
          DID-VAL
          DID
          BLID-VAL
          BLID
          FLID-VAL
          FLID
          BNID-VAL
          BNID
          FNID-VAL
          FNID
          JCT-VAL
          JCT
          BLID2-VAL
          BLID2
          BLID3-VAL
          BLID3
          BLID4-VAL
          BLID4
          FLID2-VAL
          FLID2
          FLID3-VAL
          FLID3
          FLID4-VAL
          FLID4
          CLOSSID-VAL
          CLOSSID
          SPAN-VAL
          SPAN
          LCNT-VAL
          LCNT
          LNO-VAL
          LNO
          LANETYPE-VAL
          LANETYPE
          LIMITVEL-VAL
          LIMITVEL
          REFVEL-VAL
          REFVEL
          ROADSECID-VAL
          ROADSECID
          LANECFGFG-VAL
          LANECFGFG
          LINKWAID-VAL
          LINKWAID
))