(cl:defpackage module_comm_msgs-srv
  (:use )
  (:export
   "GETIMAGEFORMAPTILE"
   "<GETIMAGEFORMAPTILE-REQUEST>"
   "GETIMAGEFORMAPTILE-REQUEST"
   "<GETIMAGEFORMAPTILE-RESPONSE>"
   "GETIMAGEFORMAPTILE-RESPONSE"
  ))

