(cl:in-package dbw_mkz_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PEDAL_INPUT-VAL
          PEDAL_INPUT
          PEDAL_CMD-VAL
          PEDAL_CMD
          PEDAL_OUTPUT-VAL
          PEDAL_OUTPUT
          TORQUE_INPUT-VAL
          TORQUE_INPUT
          TORQUE_CMD-VAL
          TORQUE_CMD
          TORQUE_OUTPUT-VAL
          TORQUE_OUTPUT
          BOO_INPUT-VAL
          BOO_INPUT
          BOO_CMD-VAL
          BOO_CMD
          BOO_OUTPUT-VAL
          BOO_OUTPUT
          ENABLED-VAL
          ENABLED
          OVERRIDE-VAL
          OVERRIDE
          DRIVER-VAL
          DRIVER
          TIMEOUT-VAL
          TIMEOUT
          WATCHDOG_COUNTER-VAL
          WATCHDOG_COUNTER
          WATCHDOG_BRAKING-VAL
          WATCHDOG_BRAKING
          FAULT_WDC-VAL
          FAULT_WDC
          FAULT_CH1-VAL
          FAULT_CH1
          FAULT_CH2-VAL
          FAULT_CH2
          FAULT_BOO-VAL
          FAULT_BOO
))