(cl:in-package dbw_mkz_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BRAKE_TORQUE_REQUEST-VAL
          BRAKE_TORQUE_REQUEST
          BRAKE_TORQUE_ACTUAL-VAL
          BRAKE_TORQUE_ACTUAL
          WHEEL_TORQUE_ACTUAL-VAL
          WHEEL_TORQUE_ACTUAL
          ACCEL_OVER_GROUND-VAL
          ACCEL_OVER_GROUND
          HSA-VAL
          HSA
          ABS_ACTIVE-VAL
          ABS_ACTIVE
          ABS_ENABLED-VAL
          ABS_ENABLED
          STAB_ACTIVE-VAL
          STAB_ACTIVE
          STAB_ENABLED-VAL
          STAB_ENABLED
          TRAC_ACTIVE-VAL
          TRAC_ACTIVE
          TRAC_ENABLED-VAL
          TRAC_ENABLED
          PARKING_BRAKE-VAL
          PARKING_BRAKE
          STATIONARY-VAL
          STATIONARY
))