(cl:in-package dbw_mkz_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TURN_SIGNAL-VAL
          TURN_SIGNAL
          HIGH_BEAM_HEADLIGHTS-VAL
          HIGH_BEAM_HEADLIGHTS
          WIPER-VAL
          WIPER
          AMBIENT_LIGHT-VAL
          AMBIENT_LIGHT
          BTN_CC_ON-VAL
          BTN_CC_ON
          BTN_CC_OFF-VAL
          BTN_CC_OFF
          BTN_CC_ON_OFF-VAL
          BTN_CC_ON_OFF
          BTN_CC_RES-VAL
          BTN_CC_RES
          BTN_CC_CNCL-VAL
          BTN_CC_CNCL
          BTN_CC_RES_CNCL-VAL
          BTN_CC_RES_CNCL
          BTN_CC_SET_INC-VAL
          BTN_CC_SET_INC
          BTN_CC_SET_DEC-VAL
          BTN_CC_SET_DEC
          BTN_CC_GAP_INC-VAL
          BTN_CC_GAP_INC
          BTN_CC_GAP_DEC-VAL
          BTN_CC_GAP_DEC
          BTN_LA_ON_OFF-VAL
          BTN_LA_ON_OFF
          BTN_LD_OK-VAL
          BTN_LD_OK
          BTN_LD_UP-VAL
          BTN_LD_UP
          BTN_LD_DOWN-VAL
          BTN_LD_DOWN
          BTN_LD_LEFT-VAL
          BTN_LD_LEFT
          BTN_LD_RIGHT-VAL
          BTN_LD_RIGHT
          FAULT_BUS-VAL
          FAULT_BUS
          DOOR_DRIVER-VAL
          DOOR_DRIVER
          DOOR_PASSENGER-VAL
          DOOR_PASSENGER
          DOOR_REAR_LEFT-VAL
          DOOR_REAR_LEFT
          DOOR_REAR_RIGHT-VAL
          DOOR_REAR_RIGHT
          DOOR_HOOD-VAL
          DOOR_HOOD
          DOOR_TRUNK-VAL
          DOOR_TRUNK
          PASSENGER_DETECT-VAL
          PASSENGER_DETECT
          PASSENGER_AIRBAG-VAL
          PASSENGER_AIRBAG
          BUCKLE_DRIVER-VAL
          BUCKLE_DRIVER
          BUCKLE_PASSENGER-VAL
          BUCKLE_PASSENGER
))