// Generated by gencpp from file module_comm_msgs/CommandWithHandshake.msg
// DO NOT EDIT!


#ifndef MODULE_COMM_MSGS_MESSAGE_COMMANDWITHHANDSHAKE_H
#define MODULE_COMM_MSGS_MESSAGE_COMMANDWITHHANDSHAKE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace module_comm_msgs
{
template <class ContainerAllocator>
struct CommandWithHandshake_
{
  typedef CommandWithHandshake_<ContainerAllocator> Type;

  CommandWithHandshake_()
    : header()
    , msg_counter(0)
    , command(0)  {
    }
  CommandWithHandshake_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , msg_counter(0)
    , command(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _msg_counter_type;
  _msg_counter_type msg_counter;

   typedef int16_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> const> ConstPtr;

}; // struct CommandWithHandshake_

typedef ::module_comm_msgs::CommandWithHandshake_<std::allocator<void> > CommandWithHandshake;

typedef boost::shared_ptr< ::module_comm_msgs::CommandWithHandshake > CommandWithHandshakePtr;
typedef boost::shared_ptr< ::module_comm_msgs::CommandWithHandshake const> CommandWithHandshakeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace module_comm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'module_comm_msgs': ['/home/dink/DINK/ros/src/msgs/platform_automation_msgs/module_comm_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bc28bf48c6bf23450157ae0aab75d4e";
  }

  static const char* value(const ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bc28bf48c6bf234ULL;
  static const uint64_t static_value2 = 0x50157ae0aab75d4eULL;
};

template<class ContainerAllocator>
struct DataType< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "module_comm_msgs/CommandWithHandshake";
  }

  static const char* value(const ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# General Command Message\n\
# Contains a command and a message counter that can be used for handshaking\n\
\n\
std_msgs/Header header\n\
\n\
uint8 msg_counter   # Increments each time a command is sent\n\
                    # An acknowledge message should be published with this value\n\
\n\
int16 command       # The command value\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.msg_counter);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandWithHandshake_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::module_comm_msgs::CommandWithHandshake_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "msg_counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_counter);
    s << indent << "command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULE_COMM_MSGS_MESSAGE_COMMANDWITHHANDSHAKE_H
