// Generated by gencpp from file module_comm_msgs/GetImageForMapTile.msg
// DO NOT EDIT!


#ifndef MODULE_COMM_MSGS_MESSAGE_GETIMAGEFORMAPTILE_H
#define MODULE_COMM_MSGS_MESSAGE_GETIMAGEFORMAPTILE_H

#include <ros/service_traits.h>


#include <module_comm_msgs/GetImageForMapTileRequest.h>
#include <module_comm_msgs/GetImageForMapTileResponse.h>


namespace module_comm_msgs
{

struct GetImageForMapTile
{

typedef GetImageForMapTileRequest Request;
typedef GetImageForMapTileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetImageForMapTile
} // namespace module_comm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::module_comm_msgs::GetImageForMapTile > {
  static const char* value()
  {
    return "a619e5a4e3af6e680da86e0d146acebe";
  }

  static const char* value(const ::module_comm_msgs::GetImageForMapTile&) { return value(); }
};

template<>
struct DataType< ::module_comm_msgs::GetImageForMapTile > {
  static const char* value()
  {
    return "module_comm_msgs/GetImageForMapTile";
  }

  static const char* value(const ::module_comm_msgs::GetImageForMapTile&) { return value(); }
};


// service_traits::MD5Sum< ::module_comm_msgs::GetImageForMapTileRequest> should match 
// service_traits::MD5Sum< ::module_comm_msgs::GetImageForMapTile > 
template<>
struct MD5Sum< ::module_comm_msgs::GetImageForMapTileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::module_comm_msgs::GetImageForMapTile >::value();
  }
  static const char* value(const ::module_comm_msgs::GetImageForMapTileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::module_comm_msgs::GetImageForMapTileRequest> should match 
// service_traits::DataType< ::module_comm_msgs::GetImageForMapTile > 
template<>
struct DataType< ::module_comm_msgs::GetImageForMapTileRequest>
{
  static const char* value()
  {
    return DataType< ::module_comm_msgs::GetImageForMapTile >::value();
  }
  static const char* value(const ::module_comm_msgs::GetImageForMapTileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::module_comm_msgs::GetImageForMapTileResponse> should match 
// service_traits::MD5Sum< ::module_comm_msgs::GetImageForMapTile > 
template<>
struct MD5Sum< ::module_comm_msgs::GetImageForMapTileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::module_comm_msgs::GetImageForMapTile >::value();
  }
  static const char* value(const ::module_comm_msgs::GetImageForMapTileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::module_comm_msgs::GetImageForMapTileResponse> should match 
// service_traits::DataType< ::module_comm_msgs::GetImageForMapTile > 
template<>
struct DataType< ::module_comm_msgs::GetImageForMapTileResponse>
{
  static const char* value()
  {
    return DataType< ::module_comm_msgs::GetImageForMapTile >::value();
  }
  static const char* value(const ::module_comm_msgs::GetImageForMapTileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_COMM_MSGS_MESSAGE_GETIMAGEFORMAPTILE_H
