// Generated by gencpp from file module_comm_msgs/RoadBoundaries.msg
// DO NOT EDIT!


#ifndef MODULE_COMM_MSGS_MESSAGE_ROADBOUNDARIES_H
#define MODULE_COMM_MSGS_MESSAGE_ROADBOUNDARIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <module_comm_msgs/LaneBoundary.h>

namespace module_comm_msgs
{
template <class ContainerAllocator>
struct RoadBoundaries_
{
  typedef RoadBoundaries_<ContainerAllocator> Type;

  RoadBoundaries_()
    : boundaries()  {
    }
  RoadBoundaries_(const ContainerAllocator& _alloc)
    : boundaries(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::module_comm_msgs::LaneBoundary_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::module_comm_msgs::LaneBoundary_<ContainerAllocator> >::other >  _boundaries_type;
  _boundaries_type boundaries;





  typedef boost::shared_ptr< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> const> ConstPtr;

}; // struct RoadBoundaries_

typedef ::module_comm_msgs::RoadBoundaries_<std::allocator<void> > RoadBoundaries;

typedef boost::shared_ptr< ::module_comm_msgs::RoadBoundaries > RoadBoundariesPtr;
typedef boost::shared_ptr< ::module_comm_msgs::RoadBoundaries const> RoadBoundariesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace module_comm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'module_comm_msgs': ['/home/dink/DINK/ros/src/msgs/platform_automation_msgs/module_comm_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9f7b0fe081428eb62b95139882c4d89";
  }

  static const char* value(const ::module_comm_msgs::RoadBoundaries_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9f7b0fe081428ebULL;
  static const uint64_t static_value2 = 0x62b95139882c4d89ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
{
  static const char* value()
  {
    return "module_comm_msgs/RoadBoundaries";
  }

  static const char* value(const ::module_comm_msgs::RoadBoundaries_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Road Boundaries Message\n\
# Contains an array of lane boundaries contained in a section of road\n\
\n\
module_comm_msgs/LaneBoundary[] boundaries\n\
\n\
\n\
================================================================================\n\
MSG: module_comm_msgs/LaneBoundary\n\
# Lane Boundary Message\n\
# Contains an array of points and other details\n\
\n\
uint8 UNKNOWN=0\n\
\n\
uint8 SOLID=1\n\
uint8 DASHED=2\n\
uint8 SOLID_DASHED=3\n\
uint8 DASHED_SOLID=4\n\
uint8 SOLID_SOLID=5\n\
uint8 style\n\
\n\
uint8 WHITE=1\n\
uint8 YELLOW=2\n\
uint8 color\n\
\n\
geometry_msgs/Point[] line\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::module_comm_msgs::RoadBoundaries_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boundaries);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadBoundaries_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::module_comm_msgs::RoadBoundaries_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::module_comm_msgs::RoadBoundaries_<ContainerAllocator>& v)
  {
    s << indent << "boundaries[]" << std::endl;
    for (size_t i = 0; i < v.boundaries.size(); ++i)
    {
      s << indent << "  boundaries[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::module_comm_msgs::LaneBoundary_<ContainerAllocator> >::stream(s, indent + "    ", v.boundaries[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULE_COMM_MSGS_MESSAGE_ROADBOUNDARIES_H
