// Generated by gencpp from file module_comm_msgs/SpeedMode.msg
// DO NOT EDIT!


#ifndef MODULE_COMM_MSGS_MESSAGE_SPEEDMODE_H
#define MODULE_COMM_MSGS_MESSAGE_SPEEDMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace module_comm_msgs
{
template <class ContainerAllocator>
struct SpeedMode_
{
  typedef SpeedMode_<ContainerAllocator> Type;

  SpeedMode_()
    : header()
    , mode(0)
    , speed(0.0)
    , acceleration_limit(0.0)
    , deceleration_limit(0.0)  {
    }
  SpeedMode_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , speed(0.0)
    , acceleration_limit(0.0)
    , deceleration_limit(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _mode_type;
  _mode_type mode;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _acceleration_limit_type;
  _acceleration_limit_type acceleration_limit;

   typedef float _deceleration_limit_type;
  _deceleration_limit_type deceleration_limit;





  typedef boost::shared_ptr< ::module_comm_msgs::SpeedMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_comm_msgs::SpeedMode_<ContainerAllocator> const> ConstPtr;

}; // struct SpeedMode_

typedef ::module_comm_msgs::SpeedMode_<std::allocator<void> > SpeedMode;

typedef boost::shared_ptr< ::module_comm_msgs::SpeedMode > SpeedModePtr;
typedef boost::shared_ptr< ::module_comm_msgs::SpeedMode const> SpeedModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::module_comm_msgs::SpeedMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace module_comm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'module_comm_msgs': ['/home/dink/DINK/ros/src/msgs/platform_automation_msgs/module_comm_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::module_comm_msgs::SpeedMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::module_comm_msgs::SpeedMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::module_comm_msgs::SpeedMode_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69d5c38e10a2546093c0ed4d98df906b";
  }

  static const char* value(const ::module_comm_msgs::SpeedMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69d5c38e10a25460ULL;
  static const uint64_t static_value2 = 0x93c0ed4d98df906bULL;
};

template<class ContainerAllocator>
struct DataType< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "module_comm_msgs/SpeedMode";
  }

  static const char* value(const ::module_comm_msgs::SpeedMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Speed Control Message with Mode\n\
# Contains speed commands and desired autonomy active mode flag\n\
\n\
std_msgs/Header header\n\
\n\
uint16 mode # Is 1 if autonomy mode should be active\n\
\n\
float32 speed                # Desired speed (m/sec)\n\
float32 acceleration_limit   # Max acceleration limit (m/sec^2)\n\
float32 deceleration_limit   # Max deceleration limit (m/sec^2)\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::module_comm_msgs::SpeedMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.speed);
      stream.next(m.acceleration_limit);
      stream.next(m.deceleration_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeedMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::module_comm_msgs::SpeedMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::module_comm_msgs::SpeedMode_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.mode);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "acceleration_limit: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration_limit);
    s << indent << "deceleration_limit: ";
    Printer<float>::stream(s, indent + "  ", v.deceleration_limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULE_COMM_MSGS_MESSAGE_SPEEDMODE_H
