(cl:in-package custom_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ITOW-VAL
          ITOW
          FIX-VAL
          FIX
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HELL-VAL
          HELL
          HMSL-VAL
          HMSL
          VEL-VAL
          VEL
          HACC-VAL
          HACC
          VACC-VAL
          VACC
          SACC-VAL
          SACC
          PDOP-VAL
          PDOP
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          NUMSAT-VAL
          NUMSAT
          HEADING-VAL
          HEADING
          HEADINGACC-VAL
          HEADINGACC
))