(cl:defpackage custom_msgs-msg
  (:use )
  (:export
   "<BAROSENSORSAMPLE>"
   "BAROSENSORSAMPLE"
   "<GNSSSENSORSAMPLE>"
   "GNSSSENSORSAMPLE"
   "<IMUSENSORSAMPLE>"
   "IMUSENSORSAMPLE"
   "<INTERNAL>"
   "INTERNAL"
   "<XSENSQUATERNION>"
   "XSENSQUATERNION"
   "<BAROSAMPLE>"
   "BAROSAMPLE"
   "<GNSSSAMPLE>"
   "GNSSSAMPLE"
   "<ORIENTATIONESTIMATE>"
   "ORIENTATIONESTIMATE"
   "<POSITIONESTIMATE>"
   "POSITIONESTIMATE"
   "<SENSORSAMPLE>"
   "SENSORSAMPLE"
   "<VELOCITYESTIMATE>"
   "VELOCITYESTIMATE"
  ))

