// Generated by gencpp from file dink_for_config_msgs/ConfigLaneSelect.msg
// DO NOT EDIT!


#ifndef dink_for_CONFIG_MSGS_MESSAGE_CONFIGLANESELECT_H
#define dink_for_CONFIG_MSGS_MESSAGE_CONFIGLANESELECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dink_for_config_msgs
{
template <class ContainerAllocator>
struct ConfigLaneSelect_
{
  typedef ConfigLaneSelect_<ContainerAllocator> Type;

  ConfigLaneSelect_()
    : header()
    , distance_threshold_neighbor_lanes(0.0)
    , lane_change_interval(0.0)
    , lane_change_target_ratio(0.0)
    , lane_change_target_minimum(0.0)
    , vector_length_hermite_curve(0.0)  {
    }
  ConfigLaneSelect_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance_threshold_neighbor_lanes(0.0)
    , lane_change_interval(0.0)
    , lane_change_target_ratio(0.0)
    , lane_change_target_minimum(0.0)
    , vector_length_hermite_curve(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _distance_threshold_neighbor_lanes_type;
  _distance_threshold_neighbor_lanes_type distance_threshold_neighbor_lanes;

   typedef float _lane_change_interval_type;
  _lane_change_interval_type lane_change_interval;

   typedef float _lane_change_target_ratio_type;
  _lane_change_target_ratio_type lane_change_target_ratio;

   typedef float _lane_change_target_minimum_type;
  _lane_change_target_minimum_type lane_change_target_minimum;

   typedef float _vector_length_hermite_curve_type;
  _vector_length_hermite_curve_type vector_length_hermite_curve;





  typedef boost::shared_ptr< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigLaneSelect_

typedef ::dink_for_config_msgs::ConfigLaneSelect_<std::allocator<void> > ConfigLaneSelect;

typedef boost::shared_ptr< ::dink_for_config_msgs::ConfigLaneSelect > ConfigLaneSelectPtr;
typedef boost::shared_ptr< ::dink_for_config_msgs::ConfigLaneSelect const> ConfigLaneSelectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dink_for_config_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dink_for_config_msgs': ['/home/dink/DINK/ros/src/msgs/dink_for_config_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68a997e92b2cc13c26ae68a329dd0433";
  }

  static const char* value(const ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68a997e92b2cc13cULL;
  static const uint64_t static_value2 = 0x26ae68a329dd0433ULL;
};

template<class ContainerAllocator>
struct DataType< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dink_for_config_msgs/ConfigLaneSelect";
  }

  static const char* value(const ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 distance_threshold_neighbor_lanes\n\
float32 lane_change_interval\n\
float32 lane_change_target_ratio\n\
float32 lane_change_target_minimum\n\
float32 vector_length_hermite_curve\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance_threshold_neighbor_lanes);
      stream.next(m.lane_change_interval);
      stream.next(m.lane_change_target_ratio);
      stream.next(m.lane_change_target_minimum);
      stream.next(m.vector_length_hermite_curve);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigLaneSelect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dink_for_config_msgs::ConfigLaneSelect_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance_threshold_neighbor_lanes: ";
    Printer<float>::stream(s, indent + "  ", v.distance_threshold_neighbor_lanes);
    s << indent << "lane_change_interval: ";
    Printer<float>::stream(s, indent + "  ", v.lane_change_interval);
    s << indent << "lane_change_target_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.lane_change_target_ratio);
    s << indent << "lane_change_target_minimum: ";
    Printer<float>::stream(s, indent + "  ", v.lane_change_target_minimum);
    s << indent << "vector_length_hermite_curve: ";
    Printer<float>::stream(s, indent + "  ", v.vector_length_hermite_curve);
  }
};

} // namespace message_operations
} // namespace ros

#endif // dink_for_CONFIG_MSGS_MESSAGE_CONFIGLANESELECT_H
